services:
  caddy-REPO_NAME:
    networks:
      - proxy
    image: pknw1/REPO_NAME:latest
    container_name: caddy-REPO_NAME
    hostname: caddy-REPO_NAME
    environment:
      - VIRTUAL_HOST=REPO_NAME
      - VIRTUAL_PORT=80

networks:
  proxy:
    external: true
    name: proxy