services:
  caddy-REPO_NAME:
    networks:
      - proxy
    image: pknw1/DOCKER_IMAGE:latest
    container_name: caddy-URL
    hostname: caddy-URL
    environment:
      - VIRTUAL_HOST=URL
      - VIRTUAL_PORT=80

networks:
  proxy:
    external: true
    name: proxy
