name: Merge

on:
  push:
    branches:
      - 'main'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          with-owner: 'false'
          string-case: 'lowercase'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build compose
        run: |
          sed -i 's/REPO_NAME/${{ steps.repo-name.outputs.repository-name }}/g' docker-compose.yml
          sed -i 's/-ENV/-prod/g' docker-compose.yml
          sed -i 's/display: flex/display: none/g' publish/*html
      - name: Build and push Docker images
        run: |
          TIMESTAMP=$(date +%s)
          echo ${TIMESTAMP} > publish/version.html
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repository-name }}:${TIMESTAMP} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repository-name }}:${TIMESTAMP}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repository-name }}:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo-name.outputs.repository-name }}:latest
      - uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ovh
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.TAILSCALE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: executing remote ssh commands using password
        if: ${{ vars.DIRECTORY_OVERRIDE == '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.TAILSCALE_SSH_SERVER }}
          username:  ${{ secrets.TAILSCALE_SSH_USER }}
          key: ${{ secrets.TAILSCALE_SSH_KEY }}
          port: ${{ secrets.TAILSCALE_SSH_SERVER_PORT }}
          script: cd cd ${{ secrets.DOCKER_ROOT }}/${{ steps.repo-name.outputs.repository-name }} && docker compose down && docker compose pull && docker compose up -d
      - name: executing remote ssh commands using password
        if: ${{ vars.DIRECTORY_OVERRIDE != '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.TAILSCALE_SSH_SERVER }}
          username:  ${{ secrets.TAILSCALE_SSH_USER }}
          key: ${{ secrets.TAILSCALE_SSH_KEY }}
          port: ${{ secrets.TAILSCALE_SSH_SERVER_PORT }}
          script: cd cd ${{ secrets.DOCKER_ROOT }}/${{ vars.DIRECTORY_OVERRIDE }} && docker compose down && docker compose pull && docker compose up -d
